# Generated by Django 5.1.2 on 2025-01-26 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0003_person_address_license'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='license_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='license',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='LicenseTracker.person'),
        ),
    ]
