# Generated by Django 5.1.2 on 2025-01-26 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0004_rename_license_number_license_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=None, max_length=50)),
                ('manufacturer', models.CharField(default=None, max_length=50)),
                ('model', models.CharField(default=None, max_length=50)),
                ('color', models.CharField(default=None, max_length=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='LicenseTracker.person')),
            ],
        ),
    ]
