# Generated by Django 5.1.2 on 2025-01-26 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0005_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='id',
        ),
        migrations.AlterField(
            model_name='license',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='LicenseTracker.person'),
        ),
    ]
