# Generated by Django 5.1.2 on 2025-01-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0006_remove_license_id_alter_license_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Junktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, unique=True)),
                ('cars', models.JSONField(default=dict)),
            ],
        ),
    ]
