# Generated by Django 5.1.2 on 2025-01-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0007_junktion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='junktion',
            name='cars',
        ),
        migrations.AddField(
            model_name='car',
            name='junktion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='LicenseTracker.junktion'),
        ),
    ]
