# Generated by Django 5.1.2 on 2025-01-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0008_remove_junktion_cars_car_junktion'),
    ]

    operations = [
        migrations.AddField(
            model_name='junktion',
            name='max_traffic',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
