# Generated by Django 5.1.2 on 2025-01-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LicenseTracker', '0009_junktion_max_traffic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='junktion',
            new_name='junction',
        ),
    ]
