from . import views
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('person/', views.view_person_info, name='sample_json_view'),
    path('make_fine/', views.make_fine, name='sample_json_view'),
    path('car/', views.view_cars, name='sample_json_view'),
    path('car_enter/', views.car_enter_junction, name='sample_json_view'),
    path('car_leave/', views.car_leave_junction, name='sample_json_view'),
    path('junction_logs/', views.junction_logs, name='sample_json_view'),
    path('create_person/', views.create_person, name='person_create'),
    path('update_person/', views.update_person, name='person_update'),
    path('delete_person/', views.delete_person, name='person_delete'),
    path('create_car/', views.create_car, name='person_create'),
    path('update_car/', views.update_car, name='person_update'),
    path('delete_car/', views.delete_car, name='person_delete'),
    path('create_license/', views.create_license, name='person_create'),
    path('update_license/', views.update_license, name='person_update'),
    path('delete_license/', views.delete_license, name='person_delete'),
    path('create_junktion/', views.create_junktion, name='person_create'),
    path('update_junktion/', views.update_junktion, name='person_update'),
    path('delete_junktion/', views.delete_junktion, name='person_delete'),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("profile/", views.profile_view, name="profile"),
    path("license/", views.license_view, name="license"),
    path("car/add/", views.car_add_view, name="car_add"),
    path("car/list/", views.car_list_view, name="car_list"),
    path("car/<int:car_id>/edit/", views.car_edit_view, name="car_edit"),
    path("car/<int:car_id>/delete/", views.car_delete_view, name="car_delete"),
    # path('carss/', include('LicenseTracker.urls')),
    # path('', views.index, name='index'),
    path("persons/", views.all_persons, name="persons_list"),
    path("licenses/", views.all_licenses, name="licenses_list"),
    path("show_cars/", views.all_cars, name="cars_list1"),
    path("connect_junctions/", views.connect_junctions, name="sample_json_view"),
    path("show_exits/", views.show_exits, name="sample_json_view"),
    path("show_traffic/", views.show_traffic, name="sample_json_view"),
    path('traffic-flow-analysis/<int:junction_id>/', views.traffic_flow_analysis, name='traffic_flow_analysis'),
    path('congestion-prediction/', views.congestion_prediction, name='congestion_prediction'),
    path('send-congestion-alert/<int:junction_id>/', views.send_congestion_alert, name='send_congestion_alert'),
    path('change_important_status/<int:car_id>/', views.change_emergency_status, name='change_emergency_status'),
    path('activate_emergency_signals/', views.activate_emergency_signals, name='activate_emergency_signals'),
    path('restore_normal_signals/', views.restore_normal_signals, name='restore_normal_signals'),
]
